name: Build and Push Docker Image

on:
  push:
    branches: ["personal"]
    tags:
      - 'v*.*.*.*'
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'patches/**'
      - 'Dockerfile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for Enterprise Edition (EE) folders
        run: |
          if [ -d "apps/server/src/ee" ] || [ -d "apps/client/src/ee" ] || [ -d "packages/ee" ]; then
            echo "--- IMPORTANT: Enterprise Edition (EE) folders detected! ---"
            echo "This fork is intended for the open-source AGPL 3.0 version."
            echo "Building with EE features is not permitted under the AGPL license."
            echo "Please remove the 'ee' directories to proceed."
            echo "This check is in place to prevent accidental builds with EE features (e.g on syncing)."
            exit 1
          fi
          echo "No Enterprise Edition (EE) folders found. Proceeding with build."

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TKN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/vito0912/forkmost
            vito0912/forkmost
          tags: |
            # Always
            type=raw,value=dev
            # For versions
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=match,pattern=v?(\d+\.\d+\.\d+\.\d+),group=0,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=match,pattern=v?(\d+\.\d+\.\d+)\.\d+,group=1,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=Forkmost
            org.opencontainers.image.description=Forkmost is a open-source collaborative wiki and documentation software with no paywalled features.